#!/usr/bin/env node

const net = require("net");
const {
  render,
  handle_input,
  handle_message,
  send_message,
  red,
} = require("./lib/helpers");
const conn = net.createConnection("./bank.sock");

const closedMessage = `The Bank is ${red("closed")}.\n`;
let beingServed = false;

function connection_ready() {
  render([closedMessage]);
	send_message(conn, 'customer')
}

function connection_closed() {
  console.log("connection closed");
}

handle_input((line) => {
	// if (line == "Hello?") {
	// 	render([closedMessage, `[ SYSTEM ] ${closedMessage}`])
	// } else if (line.includes('open')) {
	// 	render([message])
	// } else {
	// 	send_message(conn, line);
	// }
	if (!beingServed) {
		console.log(`[ SYSTEM ] You are not currently being served.`)
	}

});

handle_message(conn, (message) => {
	if (message == "Hello?") {
		render([closedMessage, `[ SYSTEM ] ${closedMessage}`])
	} else if (message.includes('open')) {
		render([message])
	} else {
		send_message(conn, message);
	}
});

conn.on("ready", connection_ready);

conn.on("close", () => {
  connection_closed();
  process.exit(1);
});

conn.on("error", () => {
  console.log("No connection");
  process.exit(1);
});
