#!/usr/bin/env node

const net = require("net");
const {
  render,
  handle_input,
  handle_message,
  send_message,
  red,
} = require("./lib/helpers");
const conn = net.createConnection("./bank.sock");

const closedMessage = `The Bank is ${red("closed")}.\n`;

function connection_ready() {
  render([closedMessage]);
	send_message(conn, 'customer')
}

function connection_closed() {
  console.log("connection closed");
}

handle_input((line) => {

  line == "Hello?"
    ? render([closedMessage, `[ SYSTEM ] ${closedMessage}`])
    : send_message(conn, line);
});

handle_message(conn, (message) => {
  console.log("Message received:", message);
});

conn.on("ready", connection_ready);

conn.on("close", () => {
  connection_closed();
  process.exit(1);
});

conn.on("error", () => {
  console.log("No connection");
  process.exit(1);
});
