#!/usr/bin/env node

const net = require('net')
const { render, handle_input, handle_message, send_message } = require('./lib/helpers')
const conn = net.createConnection('./bank.sock')



function connection_ready() {
	render([
		'Good Morning.',
		'You are not serving any customers.',
	]),
	send_message(conn, 'teller')
}



handle_input(line => {
	console.log(`Prompt command entered:`, line)
})



handle_message(conn, message => {
	if(message.includes('# customers')) {
		render([
			'Good Morning.',
			'You are not serving any customers.',
			`You have ${message.split(':')[1]} customers waiting in line.\n`
		])
	}
})










conn.on('ready', connection_ready)

conn.on('close', () => {
	console.log('connection closed')
	process.exit(1)
})

conn.on('error', () => {
	console.log('No connection')
	process.exit(1)
})